Fix Google Artifact Registry
Fixes
```
name invalid: Missing image name. Pushes should be of the form docker push HOST-NAME/PROJECT-ID/REPOSITORY/IMAGE
[ERROR]: Failed to push cache image
[ERROR]: Failed to save cache to GCR
```

Also, rename gcr to gar as GCR is gone:
https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr

diff --git a/hooks/post-command b/hooks/post-command
--- a/hooks/post-command
+++ b/hooks/post-command
@@ -39,9 +39,8 @@ main() {
   if save_cache "$provider" "$cache_key"; then
     log_success "Cache save completed!"
   else
-    log_warning "Cache save failed!"
-    # Don't fail the build if cache save fails
-    exit 0
+    log_error "Cache save failed – failing build."
+    exit 1
   fi
 }
 
